### ISSUE TITLE
Terminal Command Does Not Trigger a New Window

### ISSUE THREAD

**Issue by wynnsyt** [stuartcryan/custom-iterm-applescripts-for-alfred#10]
Another problem with running terminal commands from workflows.

If iTerm is running with no open window or tab, running the workflow simply does nothing.

I am running iTerm2 2.1.1.

**Comment by jacksleight** [comment]
+1

**Comment by anonfunc** [comment]
Pull request opened.

**Comment by stuartcryan** [comment]
Hi All,
Thank you anonfunc for the pull request, just wanted to let you know that I have seen this. Currently this weekend I am in lockdown for assignment work (assignments due Monday) so I will have a look at this within the next week.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
This code has now been merged, thanks to anonfunc for working on that :D
