### ISSUE TITLE
text instructions >>>>>>>>>> video instructions

### ISSUE THREAD

**Issue by gfarrell** [stuartcryan/custom-iterm-applescripts-for-alfred#11]
I think it would be quicker to have text instructions that detailed the installation process rather than a video. This may be a personal preference but I hate watching instruction videos, and I know a lot of developers (developers being a large part of the "target market" for this script) who feel the same way.

**Comment by stuartcryan** [comment]
Hi Gideon,
Can you please advise do you mean you want text instructions to match the video?
Cheers,
Stuart

**Comment by gfarrell** [comment]
Yes, sorry - was in a rush so that wasn't very clear - updated the issue.

**Comment by stuartcryan** [comment]
Hi Gideon,
No worries at all, currently this weekend I am in lockdown for assignment work (assignments due Monday) so I will have a look at this within the next week.
Cheers,
Stuart

**Comment by LordZardeck** [comment]
:+1: I don't like having to watch a video when it's such a simple process. Copy contents of the file respective of the version of iTerm you are using into the the custom option of Alfred's terminal preferences. Done.

**Comment by tamano** [comment]
@vitorgalvao Your instruction worked perfect for me. Thanks!
(with iTerm 2.9.x / OS X 10.10.5 / Alfred 2.8)
