### ISSUE TITLE
iTerm Opens Two Tabs

### ISSUE THREAD

**Issue by amityweb** [stuartcryan/custom-iterm-applescripts-for-alfred#13]
When I run a command in iTerm, two tabs open. The first one is just blank, then the second one is used to enter my command. 

Its annoying because I disabled the notification when quitting when a single tab, but not when multiple tabs are open. So when I run a quick terminal command then quit, I always get a Quit iTerm2? confirmation. I wouldn't get this if only one tab was open. 

Looks like its an iTerm issue thats been debated here, so sorry if you cant do anything http://www.alfredforum.com/topic/1180-extra-tab-is-open-when-using-iterm2/. Not sure if any script examples there can be used to prevent it in this script. 

Also this post may be of interest to run new commands in the current window instead of opening a new tab every time http://www.alfredforum.com/topic/721-executing-iterm2-terminal-commands-in-current-shell/?hl=iterm

**Comment by stuartcryan** [comment]
Hi amityweb,
Just wanted to let you know that I have seen your issue, currently this weekend I am in lockdown for assignment work (assignments due Monday) so I will have a look at this within the next week.
Cheers,
Stuart

**Comment by amityweb** [comment]
No probs, not a major issue, more of an annoyance, and may not even be fixable, as it may be an iTerm issue.

**Comment by stuartcryan** [comment]
Howdy my good man, just wanted to check, what version of iTerm are you using, based on "Quit iTerm2" can I assume you are running the 2.9 beta branch?
Cheers,
Stuart

**Comment by amityweb** [comment]
Build 2.1.1

**Comment by stuartcryan** [comment]
Thanks for letting me know, I will see if I am able to replicate on my VM.

**Comment by stuartcryan** [comment]
I have had a look, and the code definitely takes this into account (it was something that I specifically designed into the code and was one of the main reasons I wrote it in the first place).

Would you be open to doing a remote screensharing session by any chance (perhaps you could add me on skype StuartCRyan) as I would like to double check your setup and see why the code is not working that works around this problem.
Cheers,
Stuart

**Comment by amityweb** [comment]
Strangely I no longer get this issue now. Weird! I had the issue after installing the scripts, but no longer! 

So this can be closed, sorry to waste your time.
