### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by vitorgalvao** [stuartcryan/custom-iterm-applescripts-for-alfred#16]
By setting up [releases](https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/releases), everyone could follow new updates just by subscribing to https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/releases.atom on a feed reader, without having to watch the whole repo and get notified of every issue (which can actually makes us ignore actual releases).

**Comment by stuartcryan** [comment]
Hi Vitor,
Definitely noted - will be doing this as part of any future releases.
Cheers,
Stuart
