### ISSUE TITLE
Off topic: How are you finding iTerm 2.9?

### ISSUE THREAD

**Issue by Natetronn** [stuartcryan/custom-iterm-applescripts-for-alfred#19]
I'm curious, how are you finding iTerm 2.9 so far? Not sure I want to try it yet but, I noticed you have the second AppleScript there so, thought I'd ask what your thoughts are so far?

**Comment by stuartcryan** [comment]
Hi Nate,
I am fining it works absolutely brilliantly. I personally have no reason to look back to the old 2.1 branch.
Cheers,
Stuart
