### ISSUE TITLE
New iTerm version, new script might be needed

### ISSUE THREAD

**Issue by vitorgalvao** [stuartcryan/custom-iterm-applescripts-for-alfred#22]
From [the announcement page](https://www.iterm2.com/version3.html):
![image](https://cloud.githubusercontent.com/assets/1699443/13508793/62cde6a4-e180-11e5-863e-790d75f55b8b.png)

On the other hand, if we’re lucky [Alfred v3](https://www.alfredapp.com/blog/announcements/alfred-v3-is-coming/) will handle this correctly.

**Comment by stuartcryan** [comment]
Howdy Victor,
Long time no talk (I hope you have been well). Actually, I did some sleuthing on this as I did see the announcement from iTerm. The v3 they are putting out is just the 2.9 beta we have been running for some time. Therefore the 2.9 script is compatible with v3 as it takes into account all the new AppleScript.

It confused me initially but it now just seems that they are finally promoting the 2.9 beta as v3 (which became evident by me not finding any new version above 2.9 and when you attempt to download v3 of iTerm it actually downloads 2.9.something).

That is where I THINK we are... haha but I could very well be wrong.

I haven't been informed that Alfred will change in v3 with regards to re-introducing native support for iTerm, but I also haven't asked Andrew that question specifically either.
Stu

**Comment by stuartcryan** [comment]
Oh you have raised a valid point in my mind that I should update the metadata to identify the current script as v3 compatible though. I will get onto that today!

**Comment by stuartcryan** [comment]
All righty, metadata updated :) Vitor are you happy to have a play and confirm that the v2.9 script works for you as expected. I have been using it for ages but good to have another set of eyes.
Cheers,
Stuart

**Comment by vitorgalvao** [comment]
Hello Stuart. I have been well, thank you for asking (you’re still one of the most polite and considerate persons I’ve met online). How have you been?

Good to know extra work won’t be needed for this.

Version `2.9` of the script has been working very well for me. Though initially I was using `2.1.1`, I have switched to iTerm 2.9 some months ago, and the scripts have been working reliably.

**Comment by stuartcryan** [comment]
Heya Vitor, I am glad to hear it! (and thank you, I really appreciate it).

I have been pretty well, just getting ready for the start of semester.

Glad to hear everything is working reliably for you.
Cheers,
Stuart
