### ISSUE TITLE
Build 3.0.5 Always open new tab

### ISSUE THREAD

**Issue by AaronRanAn** [stuartcryan/custom-iterm-applescripts-for-alfred#26]
Thanks for this awesome script! 

I am using iTerm2 build 3.0.5 with custom_iterm_script_iterm_2.9.applescript, but alfred always open a new tab which I can't find a recent fix for this issue. 

Is there any update on the script to set it to always run in current session? Sorry if I missed a fix in the forum or issue. 

Many thanks!

**Comment by tconroy** [comment]
+1.... I'm on 3.0.4 and every command opens a new tab. Would appreciate a fix. Thanks for your great work on this script! 👍

**Comment by RichDonnellan** [comment]
After pasting the code into Alfred, change this line:

```diff
try
  select first window
-  set onlywindow to false
+  set onlywindow to true
```

**Comment by AaronRanAn** [comment]
works like a charm, thanks @RichDonnellan!

**Comment by tconroy** [comment]
@RichDonnellan perfect. Thank you!

**Comment by DannyFeliz** [comment]
Like a charm @AaronRanAn +1

**Comment by KittenYang** [comment]
@AaronRanAn AWESOME! THUMBS UP!👍

**Comment by jerryshew** [comment]
👍

**Comment by neverrop** [comment]
👍

**Comment by Piste** [comment]
@RichDonnellan great workaround. Or is it a fix? Should we (I'm happy to do it) modify the existing script and do a pull request? Or is this yet another (3rd?) script for a specific version of iTerm?

**Comment by stuartcryan** [comment]
This has now been merged in to the base. Apologies for the delay everyone.
