### ISSUE TITLE
2.1.1 version doesn't work..

### ISSUE THREAD

**Issue by surfjedi** [stuartcryan/custom-iterm-applescripts-for-alfred#8]
After auto upgrading my alfred, and then getting the 2.1.1 script I can no longer access iterm from alfred....  tried redo doing three times, and restarting alfred and computer but still can't use Iterm from alfred..

**Comment by stuartcryan** [comment]
Hi, can you please advise the version number is of iTerm you have installed?
Cheers,
Stuart

___________________________________________________________________

I live my life by three mottos:
1. It doesn't matter if you are laughing at me or with me... as long as you're laughing. | 2. I might have to grow old, but I will be damned if I ever have to grow up. | 3. If I can end each and every day having put at least one smile on another person's face, it has been a smashing day!

Stuart Ryan
Geek, Blogger and Senior Analyst Programmer | Connect with me on LinkedIn <http://stu.link/LINKEdin> | @StuartCRyan - Twitter <http://stu.link/FOLLOWMETWITTER> | Web: http://stuartryan.com <http://stu.link/STUARTRYAN> | Technical Blog: http://technicalnotebook.com <http://stu.link/TECHNOTEBOOK>
> On 2 Sep 2015, at 6:00 am, Lee Blazek <notifications@github.com> wrote:
> 
> After auto upgrading my alfred, and then getting the 2.1.1 script I can no longer access iterm from alfred.... tried redo doing three times, and restarting alfred and computer but still can't use Iterm from alfred..
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/issues/8>.
> 


 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet

**Comment by surfjedi** [comment]
it 2.1.1.. But no problem I have it working - I at missed a few characters in the copy and pasting. So its working now
